/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppButton {
    'color'?: 'primary' | 'success' | 'danger';
  }
  interface AppInput {
    'icon'?: string | null;
    'placeholder'?: string | null;
    /**
    * The value of the input.
    */
    'value'?: string | number | null;
  }
}

declare global {


  interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {}
  var HTMLAppButtonElement: {
    prototype: HTMLAppButtonElement;
    new (): HTMLAppButtonElement;
  };

  interface HTMLAppInputElement extends Components.AppInput, HTMLStencilElement {}
  var HTMLAppInputElement: {
    prototype: HTMLAppInputElement;
    new (): HTMLAppInputElement;
  };
  interface HTMLElementTagNameMap {
    'app-button': HTMLAppButtonElement;
    'app-input': HTMLAppInputElement;
  }
}

declare namespace LocalJSX {
  interface AppButton {
    'color'?: 'primary' | 'success' | 'danger';
  }
  interface AppInput {
    'icon'?: string | null;
    'onAppFocus'?: (event: CustomEvent<CustomEvent>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string | null;
    /**
    * The value of the input.
    */
    'value'?: string | number | null;
  }

  interface IntrinsicElements {
    'app-button': AppButton;
    'app-input': AppInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-button': LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
      'app-input': LocalJSX.AppInput & JSXBase.HTMLAttributes<HTMLAppInputElement>;
    }
  }
}


