/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppInput {
    'icon'?: string | null;
    'name': string;
    'placeholder'?: string | null;
    /**
    * The value of the input.
    */
    'value'?: string | number | null;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAppInputElement extends Components.AppInput, HTMLStencilElement {}
  var HTMLAppInputElement: {
    prototype: HTMLAppInputElement;
    new (): HTMLAppInputElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-input': HTMLAppInputElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppInput {
    'icon'?: string | null;
    'name'?: string;
    'onAppFocus'?: (event: CustomEvent<CustomEvent>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string | null;
    /**
    * The value of the input.
    */
    'value'?: string | number | null;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'app-input': AppInput;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-input': LocalJSX.AppInput & JSXBase.HTMLAttributes<HTMLAppInputElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


